APP_NAME = "Aim Companion"
APP_ID = "UnskilledSkill.AimCompanion"
VERSION = "1.9.5"
GITHUB_REPOSITORY = "Unskilled-Skill/AimCompanion"
RELEASES_URL = f"https://github.com/{GITHUB_REPOSITORY}/releases"
