APP_NAME = "Aim Companion"
APP_ID = "UnskilledSkill.AimCompanion"
VERSION = "2.0.1"
GITHUB_REPOSITORY = "Unskilled-Skill/AimCompanion"
RELEASES_URL = f"https://github.com/{GITHUB_REPOSITORY}/releases"
